version: "2.1"

services:
  angular:
    container_name: frontend
    build: ./frontend/
#    network_mode: "host"
    working_dir: /app/frontend
    env_file:
      - .env
#    environment:
#      BASE: 188.166.43.149
    ports:
      - 4200:4200
    networks:
      - wolkjes
    restart: always
    command: ng serve --host 0.0.0.0

  node:
    container_name: backend
    build: ./backend/
#   network_mode: "host"
    working_dir: /app/backend
    env_file:
      - .env
    ports:
      - 8080:8080
#    environment:
#      BASE: 188.166.43.149
    networks:
      - wolkjes
    restart: always
    command: node server.js -h 0.0.0.0

networks:
  wolkjes:
    external: true